// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoLojaAutoPeça.Context;

#nullable disable

namespace ProjetoLojaAutoPeça.Migrations
{
    [DbContext(typeof(GerenciamentoContext))]
    [Migration("20250512055843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ProjetoLojaAutoPeça.Model.ProdutosModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mercadoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ProjetoLojaAutoPeça.Model.UsuariosModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Administrador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoLojaAutoPeça.Model.VendasModel", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaDePagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdutosModelProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<int?>("UsuariosModelUsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VendaId");

                    b.HasIndex("ProdutosModelProdutoId");

                    b.HasIndex("UsuariosModelUsuarioId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("ProjetoLojaAutoPeça.Model.VendasModel", b =>
                {
                    b.HasOne("ProjetoLojaAutoPeça.Model.ProdutosModel", null)
                        .WithMany("Vendas")
                        .HasForeignKey("ProdutosModelProdutoId");

                    b.HasOne("ProjetoLojaAutoPeça.Model.UsuariosModel", null)
                        .WithMany("Vendas")
                        .HasForeignKey("UsuariosModelUsuarioId");
                });

            modelBuilder.Entity("ProjetoLojaAutoPeça.Model.ProdutosModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ProjetoLojaAutoPeça.Model.UsuariosModel", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
